language: python

services:
  - docker

python:
  - "3.6"

install:
  - docker pull mrahtz/ibd:latest

script:
  - wget -q $MUJOCO_KEY_URL -O mjkey.txt
  - |
    docker run --volume $(pwd):/interactive-behaviour-design mrahtz/ibd \
    bash -c '
      cd interactive-behaviour-design &&
      pipenv run python -u -m unittest discover -v -p "*_test.py"
    '
