language: python

services:
  - docker

python:
  - "3.6"

install:
  - docker pull mrahtz/ibd:latest

env:
  - TEST_COMMAND="pipenv run python -u -m unittest discover -v -p '*_test_long.py'"
  - TEST_COMMAND="pipenv run python -u -m unittest discover -v -p '*_test.py'"

script:
  - wget -q $MUJOCO_KEY_URL -O mjkey.txt
  - |
    docker run --volume $(pwd):/interactive-behaviour-design mrahtz/ibd \
        bash -c "cd interactive-behaviour-design && $TEST_COMMAND"
