#!/bin/bash

set -e

# If we're running on a developer's local machine or on Travis, we assume the code and the key
# are mounted at /interactive-behaviour-design
if [[ -e /interactive-behaviour-design/mjkey.txt ]]; then
    cp /interactive-behaviour-design/mjkey.txt /root/.mujoco/
fi
# If we're running on AWS, we assume the key has been put in place by the run script
# (because otherwise we'd have to store the key in the AMI, and it would be a pain to update)

# Set up display; otherwise rendering will fail
Xvfb -screen 0 1024x768x24 &
export DISPLAY=:0

# Wait for the file to come up
display=0
file="/tmp/.X11-unix/X$display"
for i in $(seq 1 10); do
    if [ -e "$file" ]; then
	break
    fi

    echo "Waiting for $file to be created (try $i/10)"
    sleep "$i"
done
if ! [ -e "$file" ]; then
    echo "Timing out: $file was not created"
    exit 1
fi

exec "$@"